import {env} from "./env"; import {getJson} from "./http"; import {haversine,scoreRoute} from "./safety"; import type {PlaceHit,LatLng,ScoredRoute,Amenity,PlanResult,RouteStep} from "./types";
export async function geocode(q:string):Promise<PlaceHit[]>{
 const u=new URL(env.nominatim+"/search");u.searchParams.set("q",q);u.searchParams.set("format","jsonv2");u.searchParams.set("limit","6");u.searchParams.set("addressdetails","1");
 const data=await getJson<any[]>(u.toString());
 return data.map(x=>({id:String(x.place_id),name:x.name||x.display_name.split(",")[0],label:x.display_name,lat:+x.lat,lng:+x.lon}));
}
async function route(a:LatLng,b:LatLng,profile="driving"){const u=`${env.osrm}/route/v1/${profile}/${a.lng},${a.lat};${b.lng},${b.lat}`;const data=await getJson<any>(u+"?overview=full&geometries=geojson&steps=true&alternatives=true");
 return data.routes as any[];
}
async function amenities(box: [number,number,number,number]):Promise<Amenity[]>{const [s,w,n,e]=box;const q=`[out:json][timeout:18];(nwr["amenity"~"police|hospital|clinic|pharmacy|fire_station"]( ${s},${w},${n},${e});nwr["shop"]( ${s},${w},${n},${e}););out center tags;`;try{const d=await getJson<any>(env.overpass,{method:"POST",headers:{"Content-Type":"text/plain"},body:q});return d.elements.map((x:any)=>{const lat=x.lat??x.center?.lat,lng=x.lon??x.center?.lon;let kind:any=x.tags?.amenity||"shop";if(kind==="fire_station")kind="fire";return {id:String(x.id),kind,name:x.tags?.name||kind,lat,lng}}).filter((x:Amenity)=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));}catch{return []}}
async function weather(p:LatLng){try{const u=new URL(env.meteo);u.searchParams.set("latitude",String(p.lat));u.searchParams.set("longitude",String(p.lng));u.searchParams.set("current","temperature_2m,precipitation,wind_speed_10m,weather_code");const d=await getJson<any>(u.toString());return {temperature:d.current?.temperature_2m??0,precipitation:d.current?.precipitation??0,wind:d.current?.wind_speed_10m??0,code:d.current?.weather_code??0};}catch{return {temperature:0,precipitation:0,wind:0,code:0}}}
function steps(r:any):RouteStep[]{return (r.legs?.[0]?.steps||[]).map((s:any)=>({instruction:s.maneuver?.instruction||s.name||"Continue",distance:s.distance,duration:s.duration,name:s.name||"",location:{lat:s.maneuver?.location?.[1]??0,lng:s.maneuver?.location?.[0]??0}}))}
function makeRoute(r:any,kind:any,a:LatLng,b:LatLng,ams:Amenity[],w:any,night:boolean):ScoredRoute{const geometry=r.geometry.coordinates.map((p:number[])=>({lat:p[1],lng:p[0]}));const s=scoreRoute({geometry,distance:r.distance,duration:r.duration},ams,night,w);return {id:kind+"-"+Math.random().toString(36).slice(2,8),kind,distance:r.distance,duration:r.duration,geometry,steps:steps(r),...s}}
export async function plan(a:LatLng,b:LatLng,preferred?:'safest'|'balanced'|'fastest'):Promise<PlanResult>{const rs=await route(a,b);const minLat=Math.min(a.lat,b.lat),maxLat=Math.max(a.lat,b.lat),minLng=Math.min(a.lng,b.lng),maxLng=Math.max(a.lng,b.lng);const pad=Math.max(.02,Math.max(maxLat-minLat,maxLng-minLng)*.15);const ams=await amenities([minLat-pad,minLng-pad,maxLat+pad,maxLng+pad]);const w=await weather(b);const night=new Date().getHours()<6||new Date().getHours()>=19;const scored=rs.map((r:any,i:number)=>makeRoute(r,i===0?"fastest":i===1?"balanced":"safest",a,b,ams,w,night));scored.sort((x,y)=>y.score-x.score);const fastest=scored.reduce((p,c)=>c.duration<p.duration?c:p,scored[0]);const safest=scored.reduce((p,c)=>c.score>p.score?c:p,scored[0]);const balanced=scored.reduce((p,c)=>Math.abs(c.score*.7+(1-c.duration/Math.max(fastest.duration*1.5,c.duration))*30-65)<Math.abs(p.score*.7+(1-p.duration/Math.max(fastest.duration*1.5,p.duration))*30-65)?c:p,scored[0]);const ordered=[preferred==='fastest'?fastest:preferred==='balanced'?balanced:safest, preferred==='fastest'?balanced:preferred==='balanced'?safest:balanced, fastest].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);return {routes:ordered,amenities:ams,brief:{headline:`${safest.score}/100 safety score`,summary:`The safest scored alternative considers mapped emergency access, nearby activity, time of day and current weather.`,watchOuts:safest.reasons,tips:["Keep location sharing available for your trusted contact.","If conditions change, ask the agent to re-plan.","Mapped amenities are signals, not guarantees of real-world safety."],sources:["OpenStreetMap/Overpass","OSRM","Open-Meteo"]},night,weather:w}}
